spring:
  application:
    name: library-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      # user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}

      # book-service
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path= /api/books/**
          filters:
            - RewritePath=/api/books/(?<segment>.*), /api/books/${segment}

      # borrowing-service
        - id: borrowing-service
          uri: lb://borrowing-service
          predicates:
            - Path= /api/borrowings/**
          filters:
            - RewritePath=/api/borrowings/(?<segment>.*), /api/borrowings/${segment}

      # notification-service
        - id: notification-service
          uri: lb://notifications-service
          predicates:
            - Path= /api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<segment>.*), /api/notifications/${segment}

#        # user-service
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path= /api/users/**
#          filters:
#            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true